### ISSUE TITLE
Incorrect German translation for temperature

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [thuryn/your-local-weather#105]
In the first diagram that shows temperature, wind and rain together, the label for temperature is translated with "Tag" (the German word for "day") if you use the German translation. The correct word would be "Temperatur".

**Comment by thuryn** [comment]
fixed in v4.6.2

**Comment by java-py-c-cpp-js** [comment]
The error still occurs in 4.6.7(FDroid), even if I reinstall the app.

**Comment by thuryn** [comment]
I've just checked the translation and yes, I can still see the wrong translation. I've fixed the translation, check the next version, please. Sorry.
