### ISSUE TITLE
Widget resets to location 0

### ISSUE THREAD

**Issue by f-viktor** [thuryn/your-local-weather#114]
The widget resets to location 0 even if it is disabled. 
After refreshing it switches to location 1 for 4-5 seconds then reverts back to location 0.
Enabling/disabling GPS has no effect

Tested on Galaxy S6 Edge /w LineageOS 14.1

I really just wanna set a location and forget about it, instead of it having to update my location while draining battery.

**Comment by thuryn** [comment]
which widget do you use?

**Comment by f-viktor** [comment]
4x3 with normal forecast (not graph)

I was able to resolve this today, with the following steps:
1 - setting a location 0 by allowing gps,
2 - disabling location 0 again
3 - changing widget actions and tapping the location (I assumed that would cause it to rotate location)

Not sure what part did it, but I have a hunch it was forcing the widget to change location, even though there was only 1 location enabled.

**Comment by skkayman** [comment]
All of the widgets I tried are doing it. It shows 27°C temperature, "Location not found" because it did not found the location by GPS. Location 0 is disabled. Even the graph of next few days is 27 and plus minus 1-2 degrees. NExt 5 days are 27/27, 26/28, 27/28, 26/27, 27/27.

This is great weather apps with beautiful widget, I hope you get it fixed.

**Comment by thuryn** [comment]
I believe I found the root cause of the problem. The solution probably solves the problems addressed by issues #84 #100 #111

I'm working on the solution.

**Comment by thuryn** [comment]
Could you, please, try the (prerelease) version here: https://de-next.owncube.com/index.php/s/zie8dYZqT63W7q4

**Comment by skkayman** [comment]
It seems to be fixed! But I am still getting a message "Permissions are not yet granted - click the location symbol in the app". I have not granted calls permission.. :)

**Comment by skkayman** [comment]
It does on update but even when I unlock the phone. But location 0 has no influence in it, can be enabled and disabled. It is only with this prerelease apk.

Update for Location 0 - every hour (if it is enabled)
Update period for Loc 1,2,.. - 15 minutes
Location and Address Source - Local MLS and Nominatim

Wake-Up strategy - CPU
Switch GPS on when necessary - enabled
Found locations are cached

Widget settings - all options disabled

It is the call access permission not granted it is says I believe but why always on update?

**Comment by thuryn** [comment]
I've just fixed it and uploaded the new version.

**Comment by skkayman** [comment]
It seems to be working fine now! Good job :)

**Comment by thuryn** [comment]
ok, thank you for the message
